server.port: 8080
logging.config: classpath:config/logback.xml
server.contextPath: /questionnaire

liquibase:
  change-log: classpath:liquibase/migration.yml
  contexts: common
spring.datasource:
  url: jdbc:postgresql://postgresql-questionnaire:5432/galandor?currentSchema=questionnaire&connectTimeout=120
  username: galandor
  password: qwerty
  min-idle: 4
  max-idle: 8
  max-active: 8
  max-wait: 60000
  test-on-borrow: true
  validation-interval: 5000
  validation-query: SELECT 1;
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
